site_name: Sweatpy docs

theme:
    name: 'material'
    palette:
        primary: 'blue grey'
        accent: 'red'
    icon:
        logo: fontawesome/solid/tint
        repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      toc_depth: 2

repo_name: goldencheetah/sweatpy
repo_url: https://github.com/goldencheetah/sweatpy

plugins:
  - mknotebooks

nav:
    - 'index.md'
    - 'Features':
        - 'features/Critical power.ipynb'
        - 'features/nomenclature.md'
        - 'features/data_loading.md'
        - 'features/example_data.md'
    - 'changelog.md'
    - 'contributing.md'
